### ISSUE TITLE
How to generate count matrix after generating output from kallisto pseudo

### ISSUE THREAD

**Issue by jojikt2007** [pachterlab/BYVSTZP_2020#1]
Can you guide me how to generate count matrix after generating output from kallisto pseudo --quant -i reference/index.idx -o ./mop_SMARTseq/out/ -b smart-seq_batch.txt -t 16 for downstream alalysis in SMART-SEQ2

I got this many files from Kallisto pseudo --quant

1, matrix.abundance.mtx
2, matrix.cells
3, matrix.ec
4, matrix.fld.tsv
5, matrix.tcc.mtx
6, run_info.json
7, transcripts.txt

Which file I should use for generating isoform count matrices file for downstream analysis. also i would like to know how did create "adata.h5ad" file?

Thanks
JKT

**Comment by arshiyaakeel** [comment]
Hello JKT,

Could you manage to get count matrix?

Thank you.

Best

ASh

**Comment by sbooeshaghi** [comment]
Please see this script: https://github.com/pachterlab/BYVSTZP_2020/blob/master/analysis/scripts/make_adata.py
