### ISSUE TITLE
Understanding the Output of Kallisto Pseudo-Alignment

### ISSUE THREAD

**Issue by arshiyaakeel** [pachterlab/BYVSTZP_2020#2]
Hello, 
I am running the following command for only one sample (two fastq files only):

time kallisto pseudo --quant  -i indices/Kallisto/transcripts.idx -o results/Kallisto -b batch.txt -t 16

The command is producing only 4 files - matrix.cells, matrix.ec, matrix.tsv and run_info.json.

I am wondering if these files can be used to get the expression data matrix for further analysis as some files are missing such as matrix.abundance.mtx, transcripts.txt etc.

Any suggestion will be appreciated.

Thank you. 
AA

**Comment by sbooeshaghi** [comment]
Hi @arshiyaakeel, to generate an expression matrix, please use `kallisto pseudo --quant` with the `-b` batch option and the batch file (as is done here: https://github.com/pachterlab/BYVSTZP_2020/blob/master/analysis/scripts/kallisto_smart-seq.sh) and then  you can generate an annotated dataframe from the output of `kallisto pseudo --quant` using the https://github.com/pachterlab/BYVSTZP_2020/blob/master/analysis/scripts/make_adata.py file.
