### ISSUE TITLE
kallisto pseudo to seurat 

### ISSUE THREAD

**Issue by jmzvillarreal** [pachterlab/BYVSTZP_2020#3]
Hi,
I ran kallisto pseudo on smartseq2 sc data and obtained these output files:
matrix.abundance.mtx  matrix.cells  matrix.ec  matrix.fld.tsv  matrix.tcc.mtx  run_info.json  transcripts.txt
I want to load those into seurat and the only tip I found was:
https://github.com/paulranum11/kallisto_pseudo_to_expressionMatrix
which starts from slightly different outputs (i believe generated from previous versions of kallisto)
Could you please help me out ?
Thanks !
Jaime.

**Comment by sbooeshaghi** [comment]
Please see here for how to generate an h5ad object: https://github.com/pachterlab/BYVSTZP_2020/issues/1#issuecomment-720000772

You can then load the h5ad file into Seurat.

**Comment by mkalisz1805** [comment]
Hi,
I have generated the h5ad object and loaded it into Seurat, but the object contains a sparse matrix with transcript IDs.
Could you please help me how to collapse this matrix to gene IDs?
Should this be done prior to making the h5ad file and if so, can you advice how to do it?
Thanks!
Mark
