### ISSUE TITLE
Collapsing transcript IDs to gene IDs in h5ad object

### ISSUE THREAD

**Issue by mkalisz1805** [pachterlab/BYVSTZP_2020#5]
Hi,
I have generated the h5ad object from Kallisto pseudo output files using your script make_adata.py.
Next I loaded it into Seurat, but the object contains a sparse matrix with transcript IDs.
Could you please help me how to collapse this matrix to gene IDs?
Should this be done prior to making the h5ad file and if so, can you advice how to do it?
Thanks!
Mark

**Comment by sbooeshaghi** [comment]
Check out cell 25 for how to collapse isoforms into genes: https://github.com/pachterlab/BYVSTZP_2020/blob/master/analysis/notebooks/final-make_smartseq_gene_isoform_adata.ipynb

**Comment by jma1991** [comment]
Sorry to re-open this issue, but I am confused more generally about how to summarise transcript-level abundance estimates to gene-level counts. In cell 25 of the analysis document it seems you drop any duplicate rows (i.e. transcripts) leaving just a single representative transcript for the gene - is that correct? Is there no summarisation method similar to how tximport handles kallisto quant output?

**Comment by sbooeshaghi** [comment]
To go from transcript-level abundance estimates to gene-level estimates we sum the length-normalized transcript estimates for a single gene. This is explained in the methods section of the manuscript that this repository corresponds to: https://www.biorxiv.org/content/10.1101/2020.03.05.977991v3.

The confusion may arise from this snippet of code:
```python
    # array of unique targets
    unique = s2t[target_id].unique().astype(str)
    nuniq = unique.shape[0]
    X = np.zeros((ncomp, nuniq))
```

The naming of the variables is a bit misleading. In very rare cases the same transcript (in name) can come from multiple reference builds, i.e. GENCODE or Ensembl; the purpose of writing this function in this way was to make it general enough to account for this possibility. This does not discard the multiple transcripts that come from a single gene. One can verify this is true by taking the gene matrix and the isoform matrix and summing the estimates for a single gene. I don't know how tximport works so I cannot comment on how this method compares to it for handling kallisto quant output.

I hope that helps!

**Comment by jma1991** [comment]
Okay, I understand now. Thank you.

**Comment by houruiyan** [comment]
Sorry to reopen this. I am a little confused. The passage said that "Isoform and gene-count matrices were generated for the Smart-seq2 data using the kallisto pseudo command." That means that you use the kallisto peudo quant to produce the gene count seperately? The former uses the transcript index, the latter used the gene index. Then why you want to try produce the gene-count matrix from isoform-count matrix? Hope to get your answer. Thank you!
