### ISSUE TITLE
abundance file not generated

### ISSUE THREAD

**Issue by jkniehaus** [pachterlab/BYVSTZP_2020#7]
Hi @sbooeshaghi,
I'm trying to quantify multiple paired-end fastq files from single-cell smartseq data similar to what was done in the corresponding publication
.
I'm experiencing an issue with quantification of a batch (testing n=2 cells) fastq files where `kallisto pseudo --quant` does not provide the abundance matrix needed to generate a cells x transcripts matrix.

 The `kallisto pseudo --quant` with `-b` batch option + file either does not recognize the `--quant` command (`pseudo: unrecognized option '--quant'`; v0.44.0), or I get a segmentation error:
 `[quant] finding pseudoalignments for all files .../var/spool/slurmd/job35157683/slurm_script: line 4: 251503 Segmentation fault `
 (v0.43.1 & v0.46.1). 
 
 The command I'm using is:
 `kallisto pseudo --quant -i /path/to/transcriptome.idx -o kallisto/out/ -b seq_batch.txt -t 8`
 
Any guidance would be a big help.

Thanks!

**Comment by sbooeshaghi** [comment]
Hey Jesse, can you try updating kallisto to 0.46.2? 

https://github.com/pachterlab/kallisto/releases/tag/v0.46.2

If you still run into problems please let me know!

**Comment by jkniehaus** [comment]
Worked like a charm! 
Forgive my naivety, probably should've checked that first.
Thanks!
