### ISSUE TITLE
gene-count matrix

### ISSUE THREAD

**Issue by houruiyan** [pachterlab/BYVSTZP_2020#8]
Dear Dr. 
I am a little confused. The passage said that "Isoform and gene-count matrices were generated for the Smart-seq2 data using the kallisto pseudo command." That means that you use the kallisto peudo quant to produce the gene count seperately? The former uses the transcript index, the latter used the gene index. Then why you want to try produce the gene-count matrix from isoform-count matrix? Hope to get your answer. Thank you!

**Comment by sbooeshaghi** [comment]
The kallisto pseudo command was used to generate the transcript count matrix. Gene count matrices were created by summing the counts for all transcripts in the gene

**Comment by houruiyan** [comment]
ok thank you very much!

**Comment by ryotamura315** [comment]
Dear Kallisto team,

Related to this topic, we would like to generate cell x isoform matrices from smart-seq2 data using pseudo command based on your scripts in https://github.com/pachterlab/BYVSTZP_2020/blob/master/analysis/scripts/kallisto_smart-seq.sh. 
and 
https://github.com/pachterlab/BYVSTZP_2020/blob/master/analysis/scripts/batch.sh

If I understand correctly, the batch.txt should contain thousands of rows of cell barcodes and corresponding fastq.gz files, which would then result in cell x isoform matrices through Kallisto pseudo command. To study how your codes work to produce such a batch file, we wanted to look at "../data/SMARTseq/smart-seq_batch.txt" and "../data/SMARTseq/fastqs/*.tar" , but these files are not currently accessible. Is there any way we can access these files? Thanks you so much.

**Comment by sbooeshaghi** [comment]
Those files are the actual SMARTseq FASTQ files. We have upgrade `kb_python` to enable easy SMARTseq processing (https://github.com/pachterlab/kb_python/releases); @Lioscro has made that possible. Please give it a try!
